# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  driver: "gd"
  twig:
    mode: lazy
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: "media/cache"
  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/public"
  filter_sets:
    # Configuration de base pour les images WebP avec qualité optimisée
    webp_optimized:
      quality: 85 # Qualité de compression
      format: webp # Format WebP
      filters:
        # Taille par défaut
        thumbnail: { size: [1200, 800], mode: inset }

    # Miniature pour petites vignettes
    thumbnail_small:
      quality: 85
      format: webp
      filters:
        thumbnail: { size: [180, 160], mode: inset }

    # Taille moyenne pour affichages intermédiaires
    thumbnail_medium:
      quality: 85
      format: webp
      filters:
        thumbnail: { size: [300, 200], mode: inset }

    # Taille large pour affichages de grande qualité
    thumbnail_large:
      quality: 85
      format: webp
      filters:
        thumbnail: { size: [800, 600], mode: inset }

    # Grand format pour affichages plein écran
    fullscreen:
      quality: 85
      format: webp
      filters:
        thumbnail: { size: [1920, 1080], mode: inset }

    # Cache général
    cache: ~

